config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    resource :profile, only: %i[show]

    namespace :admin do
      root 'bulletins#index', filter: :under_moderation

      resources :bulletins, only: %i[index], filter: :all do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
    scope :auth, module: :auth do
      post :logout, action: :logout, as: :auth_logout
      post ':provider', action: :request, as: :auth_request
      get ':provider/callback', action: :callback, as: :callback_auth
    end
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

module Web
  class ProfilesController < Web::ApplicationController
    before_action :check_current_user

    def show
      @q = current_user.bulletins.ransack(params[:q])
      @bulletins = @q
                   .result
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(12)
    end
  end
end

app/helpers/web/profile/bulletins_helper.rb
# frozen_string_literal: true

module Web
  module Profile
    module BulletinsHelper
      def bulletin_states_as_options
        db_states = Bulletin.aasm.states.map(&:name)
        db_states.map { |state| [t("web.profile.bulletins.index.state.#{state}"), state] }
      end
    end
  end
end

app/views/web/profiles/_actions.html.slim
= link_to t('.show'), bulletin,
  class: 'me-2'

= link_to t('.edit'), edit_bulletin_path(bulletin),
  class: 'me-2'

- if bulletin.may_to_moderate?
  = link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin),
    data: { turbo_method: :patch, turbo_confirm: t('.confirm.to_moderate') },
    class: 'me-2'

-if bulletin.may_archive?
  = link_to t('.archive'), archive_bulletin_path(bulletin),
    data: { turbo_method: :patch, turbo_confirm: t('.confirm.archive') },
    class: 'text-danger'

app/views/web/profiles/_search_form.html.slim
= search_form_for @q, url: profile_path do |f|
  .row.my-2
    .col-6
      = f.input :title_cont, label: false, hint: t('.hint.title')
    .col-4
      = f.input :state_eq,
        as: :select,
        collection: bulletin_states_as_options,
        label: false,
        hint: t('.hint.state')
    .col-2
      = f.button :submit, class: 'btn btn-primary me-2'
      = link_to t('.reset'), bulletins_path, class: 'btn btn-outline-primary'

app/views/web/profiles/show.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .row
    .p-3.p-lg-5.pt-lg-0
      .mb-4
        h2 = t('.title')
        hr
      = link_to t('.new_bulletin'), new_bulletin_path
      = render 'search_form', bulletins: @bulletins
      .row.mt-2
        table.table.table-borderless
          thead
            tr
              th = t('.col.name')
              th = t('.col.state')
              th = t('.col.created_at')
              th = t('.col.actions')
          tbody
            - @bulletins.each do |bulletin|
                tr
                  td = bulletin.title
                  td = t(".state.#{bulletin.state}")
                  td = time_ago_in_words(bulletin.created_at)
                  td = render 'actions', bulletin:
        = paginate @bulletins