config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    resource :profile, only: %i[show]

    namespace :admin do
      root 'bulletins#index', filter: :under_moderation

      resources :bulletins, only: %i[index], filter: :all do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
    scope :auth, module: :auth do
      post :logout, action: :logout, as: :auth_logout
      post ':provider', action: :request, as: :auth_request
      get ':provider/callback', action: :callback, as: :callback_auth
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#
class Category < ApplicationRecord
  has_many :bulletins, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[id]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['bulletins']
  end
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class CategoriesController < Web::Admin::ApplicationController
      before_action :set_category, only: %i[edit update destroy]

      def index
        @categories = Category.all
      end

      def new
        @category = Category.new
      end

      def edit; end

      def create
        @category = Category.new(category_params)

        if @category.save
          redirect_to admin_categories_path, notice: t('.notice')
        else
          flash[:alert] = t('.alert')
          render :new, status: :unprocessable_entity
        end
      end

      def update
        if @category.update(category_params)
          redirect_to admin_categories_path, notice: t('.notice')
        else
          flash[:alert] = t('.alert')
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        if @category.bulletins.any?
          flash[:alert] = t('.alert')
        else
          @category.destroy!
          flash[:notice] = t('.notice')
        end
        redirect_to admin_categories_url
      end

      private

      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name)
      end
    end
  end
end

app/helpers/web/categories_helper.rb
# frozen_string_literal: true

module Web
  module CategoriesHelper
  end
end

app/views/web/admin/categories/_form.html.slim
= simple_form_for [:admin, category] do |f|
  = f.input :name
  = f.button :submit, class: 'btn btn-primary'

app/views/web/admin/categories/edit.html.slim
.row
  = render 'web/admin/nav'
  .col-md-9
    h1.h2.mb-4 = t('.title')
    = render 'form', category: @category

app/views/web/admin/categories/index.html.slim
.row
  = render 'web/admin/nav'
  .col-md-9
    h1.h2.mb-4 = t('.title')
    = link_to t('add_category'), new_admin_category_path
    .row.mt-2
      table.table.table-borderless
        thead
          tr
            th = t('.id')
            th = t('.name')
            th = t('.actions')
        tbody
          - @categories.each do |category|
            tr
              td = category.id
              td = category.name
              td
                = link_to t('.edit'), edit_admin_category_path(category)
                = link_to t('.destroy'),
                  admin_category_path(category),
                  class: 'ms-2 text-danger',
                  data: { turbo_method: :delete,
                    turbo_confirm: t('.confirm_destroy') }

app/views/web/admin/categories/new.html.slim
.row
  = render 'web/admin/nav'
  .col-md-9
    h1.h2.mb-4 = t('.title')
    = render 'form', category: @category