config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :archive
        patch :to_moderate
      end
    end

    resource :profile, only: %i[show]

    namespace :admin do
      root 'bulletins#index', filter: :under_moderation

      resources :bulletins, only: %i[index], filter: :all do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
    scope :auth, module: :auth do
      post :logout, action: :logout, as: :auth_logout
      post ':provider', action: :request, as: :auth_request
      get ':provider/callback', action: :callback, as: :callback_auth
    end
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bulletins
#
#  id          :integer          not null, primary key
#  description :text             not null
#  state       :string           default("draft")
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer          not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_bulletins_on_category_id  (category_id)
#  index_bulletins_on_user_id      (user_id)
#
# Foreign Keys
#
#  category_id  (category_id => categories.id)
#  user_id      (user_id => users.id)
#
class Bulletin < ApplicationRecord
  include AASM
  belongs_to :user
  belongs_to :category

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, attached: true,
                    content_type: %i[png jpg jpeg],
                    size: { less_than: 5.megabytes }

  aasm column: :state do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[category image_attachment image_blob user]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[state title]
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < Web::Admin::ApplicationController
      before_action :set_bulletin, only: %i[publish reject archive]
      after_action :verify_authorized, only: %i[publish reject archive]

      def index
        @q = Bulletin.send(params[:filter]).includes(:user).ransack(params[:q])
        @bulletins = @q
                     .result
                     .page(params[:page])
      end

      def publish
        authorize @bulletin
        if @bulletin.may_publish?
          @bulletin.publish!
          flash[:notice] = t('.notice')
        else
          flash[:alert] = t('.alert')
        end
        redirect_to admin_root_path
      end

      def reject
        authorize @bulletin
        if @bulletin.may_reject?
          @bulletin.reject!
          flash[:notice] = t('.notice')
        else
          flash[:alert] = t('.alert')
        end
        redirect_to admin_root_path
      end

      def archive
        authorize @bulletin
        if @bulletin.may_archive?
          @bulletin.archive!
          flash[:notice] = t('.notice')
        else
          flash[:alert] = t('.alert')
        end
        redirect_to admin_root_path
      end

      private

      def set_bulletin
        @bulletin = Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < Web::ApplicationController
    before_action :set_bulletin, only: %i[show edit update archive to_moderate]
    after_action :verify_authorized, only: %i[show new create edit update archive to_moderate]

    def index
      @q = Bulletin.published.ransack(params[:q])
      @bulletins = @q
                   .result
                   .with_attached_image
                   .includes(:category)
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(12)
    end

    def show
      authorize @bulletin
    end

    def new
      @bulletin = Bulletin.new
      authorize @bulletin
    end

    def edit
      authorize @bulletin
    end

    def create
      @bulletin = Bulletin.new(bulletin_params)
      authorize @bulletin

      @bulletin.user = current_user

      if @bulletin.save
        redirect_to profile_path, notice: t('.notice')
      else
        flash[:alert] = t('.alert')
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize @bulletin

      if @bulletin.update(bulletin_params)
        redirect_to profile_path, notice: t('.notice')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def to_moderate
      authorize @bulletin
      if @bulletin.may_to_moderate?
        @bulletin.to_moderate!
        flash[:notice] = t('.notice')
      else
        flash[:alert] = t('.alert')
      end
      redirect_to profile_path
    end

    def archive
      authorize @bulletin
      if @bulletin.may_archive?
        @bulletin.archive!
        flash[:notice] = t('.notice')
      else
        flash[:alert] = t('.alert')
      end
      redirect_to profile_path
    end

    private

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :category_id, :image)
    end

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end
  end
end

app/helpers/web/admin/bulletins/search_form_helper.rb
# frozen_string_literal: true

module Web
  module Admin
    module Bulletins
      module SearchFormHelper
        def categories_as_options
          Category.all.map { |category| [category.name, category.id] }
        end
      end
    end
  end
end

app/helpers/web/bulletins_helper.rb
# frozen_string_literal: true

module Web
  module BulletinsHelper
    def categories_as_options
      Category.all.map { |category| [category.name, category.id] }
    end
  end
end

app/helpers/web/profile/bulletins_helper.rb
# frozen_string_literal: true

module Web
  module Profile
    module BulletinsHelper
      def bulletin_states_as_options
        db_states = Bulletin.aasm.states.map(&:name)
        db_states.map { |state| [t("web.profile.bulletins.index.state.#{state}"), state] }
      end
    end
  end
end

app/views/web/admin/bulletins/_actions.html.slim
- if params[:filter] == :all

  = link_to t('.show'), bulletin,
    class: 'me-2'

- elsif params[:filter] == :under_moderation

  - if bulletin.may_publish?
    = link_to t('.publish'), publish_admin_bulletin_path(bulletin),
      data: { turbo_method: :patch, turbo_confirm: t('.confirm.publish') },
      class: 'me-2'

  - if bulletin.may_reject?
    = link_to t('.reject'), reject_admin_bulletin_path(bulletin),
      data: { turbo_method: :patch, turbo_confirm: t('.confirm.reject') },
      class: 'me-2'

- if bulletin.may_archive?
  = link_to t('.archive'), archive_admin_bulletin_path(bulletin),
    data: { turbo_method: :patch, turbo_confirm: t('.confirm.archive') },
    class: 'text-danger'

app/views/web/admin/bulletins/_search_form.html.slim
= search_form_for @q, url: admin_bulletins_path do |f|
  = f.label :title_cont 
  = f.search_field :title_cont

  = f.label :category_id_eq
  - categories_options = Category.all.map { |category| [category.name, category.id] }
  = f.collection_select :category_id_eq, categories_options, :last, :first, include_blank: true

  = f.submit
  = link_to t('.reset'), admin_bulletins_path

app/views/web/admin/bulletins/index.html.slim
.row
  = render 'web/admin/nav'
  .col-md-9
    h1.h2.mb-4 = t('.title')
    = render 'search_form'
    .row.mt-2
      table.table.table-borderless
        thead
          tr
            th = t('.cell_name')
            - if params[:filter] == :all
              th = t('.cell_state')
            th = t('.cell_created_at')
            th = t('.cell_actions')
        tbody
          - @bulletins.each do |bulletin|
            tr
              td = link_to bulletin.title, bulletin
              - if params[:filter] == :all
                td = t(".state.#{bulletin.state}")
              td = time_ago_in_words(bulletin.created_at)
              td = render 'actions', bulletin:
      = paginate @bulletins